"""empty message

Revision ID: 5428cc4f56dd
Revises: 23e9bb46495f
Create Date: 2020-01-23 22:16:58.191774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5428cc4f56dd'
down_revision = '23e9bb46495f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_table', sa.Column('string_field_2', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_table', 'string_field_2')
    # ### end Alembic commands ###
